### ISSUE TITLE
chrome crashes

### ISSUE THREAD

**Issue by anotherbird** [aflansburg/amzreviewsscrape#3]
..the culprit error - DevTools
add please in helpers:
```
options.add_argument("--disable-dev-shm-usage")
options.add_argument('--no-sandbox')
```
thanks

**Comment by aflansburg** [comment]
Apologies for letting this slide for so long.

**Comment by aflansburg** [comment]
This is fixed now and arguments added in https://github.com/aflansburg/amzreviewsscrape/pull/8
