### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by AnimagusDove** [aflansburg/amzreviewsscrape#7]
Hi, I followed your instructions but it seems that the program stuck at line 54 in **helpers.py**.

Kindly find the info below:

  File "/Users/lib/python3.7/asin/helpers.py", line 54, in read_reviews
    **total_reviews = int(total_reviews.text.replace(",",""))**
AttributeError: 'NoneType' object has no attribute 'text'

Could you help to fix it? Thank you very much!

**Comment by LumosLiang** [comment]
@AnimagusDove 

I think the following code is the correct way to get the total_reviews value now:
`total_reviews = soup.find('div', {'class': 'a-row a-spacing-base a-size-base'})`

**Comment by aflansburg** [comment]
@AnimagusDove Thanks! The HTML structure changed a bit and I fell behind in keeping this repo up. My apologies. Updated and fixed via this commit https://github.com/aflansburg/amzreviewsscrape/commit/c4ac2fa45a4b1cdd78c6d969dac282d3a8ec1ad6
